<?php

use App\City;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

$cities = array(
    0 => array('city_name' => 'ABBOTABAD', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    2 => array('city_name' => 'ADDA JOHAL 97 / RB', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    1 => array('city_name' => 'ABDUL HAKIM', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    3 => array('city_name' => 'ADDA SHEIKH WAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    4 => array('city_name' => 'ADDA SIRAJ', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    5 => array('city_name' => 'AHMED PUR EAST', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    6 => array('city_name' => 'AHMED PUR SIAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    7 => array('city_name' => 'AJNIA WALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    8 => array('city_name' => 'AKHTAR ABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    9 => array('city_name' => 'AKORA KHATAK', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    10 => array('city_name' => 'ALI PUR CHATHA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    11 => array('city_name' => 'ALIPUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    12 => array('city_name' => 'ALLAH ABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    13 => array('city_name' => 'AMANGARH', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    14 => array('city_name' => 'ARIFWALA', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    15 => array('city_name' => 'ATTOCK', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    16 => array('city_name' => 'AYUBIA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    17 => array('city_name' => 'BADIN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    18 => array('city_name' => 'BADOMALI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    19 => array('city_name' => 'BAFFA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    20 => array('city_name' => 'BAGH', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    21 => array('city_name' => 'BAGHATANWALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    22 => array('city_name' => 'BAHAWALNAGAR', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    23 => array('city_name' => 'BAHAWALPUR', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    24 => array('city_name' => 'BAHTAR MORE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    25 => array('city_name' => 'BAIG PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    26 => array('city_name' => 'BALAM BUT', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    27 => array('city_name' => 'BANNU', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    28 => array('city_name' => 'BARA MARKET', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    29 => array('city_name' => 'BARAH KHU', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    30 => array('city_name' => 'BARI KOT', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    31 => array('city_name' => 'BASHARAT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    32 => array('city_name' => 'BASIRPUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    33 => array('city_name' => 'BASTI MALOOK', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    34 => array('city_name' => 'BATGRAM', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    35 => array('city_name' => 'BATKHELA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    36 => array('city_name' => 'BHAI PHERU', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    37 => array('city_name' => 'BHAKKAR', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    38 => array('city_name' => 'BHALWAAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    39 => array('city_name' => 'BHERA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    40 => array('city_name' => 'BHIKKI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    41 => array('city_name' => 'BHIMBER (AJK)', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    42 => array('city_name' => 'BHOWANA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    43 => array('city_name' => 'BHURBUN (P.C. HOTEL)', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    44 => array('city_name' => 'BONGA HAYAT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    45 => array('city_name' => 'BUCHEKE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    46 => array('city_name' => 'BUNER', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    47 => array('city_name' => 'BUREWALA', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    48 => array('city_name' => 'CADET COLLEGE SUNNY BANK', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    49 => array('city_name' => 'CHAK JHUMRA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    50 => array('city_name' => 'CHAK PARANA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    51 => array('city_name' => 'CHAKDARA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    52 => array('city_name' => 'CHAKLALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    53 => array('city_name' => 'CHAKRI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    54 => array('city_name' => 'CHAKWAL', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    55 => array('city_name' => 'CHAMAN', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    56 => array('city_name' => 'CHANGA MANGA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    57 => array('city_name' => 'CHAR BAGH', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    58 => array('city_name' => 'CHARSADDA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    59 => array('city_name' => 'CHAWINDA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    60 => array('city_name' => 'CHICHAWATNEE', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    61 => array('city_name' => 'CHINIOT', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    62 => array('city_name' => 'CHISTIAN', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    63 => array('city_name' => 'CHITRAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    64 => array('city_name' => 'CHOA SAIDAN SHAH', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    65 => array('city_name' => 'CHOBARA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    66 => array('city_name' => 'CHOTA LAHORE', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    67 => array('city_name' => 'CHOWK AZAM', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    68 => array('city_name' => 'CHOWK PANDORI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    69 => array('city_name' => 'CHUNIAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    70 => array('city_name' => 'DADU', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    71 => array('city_name' => 'DADYAL (AJK)', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    72 => array('city_name' => 'DAKWALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    73 => array('city_name' => 'DALBANDIN', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    74 => array('city_name' => 'DAOOD ZAI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    75 => array('city_name' => 'DARGAI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    76 => array('city_name' => 'DARYA KHAN', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    77 => array('city_name' => 'DASKA', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    78 => array('city_name' => 'DAUL TALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    79 => array('city_name' => 'DEHARKI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    80 => array('city_name' => 'DEPALPUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    81 => array('city_name' => 'DERA ALLAH YAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    82 => array('city_name' => 'DERA GHAZI KHAN', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    83 => array('city_name' => 'DERA ISMAIL KHAN', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    84 => array('city_name' => 'DERA MURAD JAMALI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    85 => array('city_name' => 'DERA NAWAB', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    86 => array('city_name' => 'DEWALAY', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    87 => array('city_name' => 'DHABJEE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    88 => array('city_name' => 'DHUDIAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    89 => array('city_name' => 'DIGRI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    90 => array('city_name' => 'DIJKOT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    91 => array('city_name' => 'DINA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    92 => array('city_name' => 'DINGA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    93 => array('city_name' => 'DISTT. COMPLEX', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    94 => array('city_name' => 'DOABA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    95 => array('city_name' => 'DOKRI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    96 => array('city_name' => 'DONGA BONGA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    97 => array('city_name' => 'DULLE WALA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    98 => array('city_name' => 'DUNIAPUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    99 => array('city_name' => 'F.F.C. PLANT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    100 => array('city_name' => 'FAISALABAD', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    101 => array('city_name' => 'FAQIRWALI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    102 => array('city_name' => 'FAROKA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    103 => array('city_name' => 'FAROOQABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    104 => array('city_name' => 'FATEH JANG', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    105 => array('city_name' => 'FATEH PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    106 => array('city_name' => 'FATEH PUR KAMAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    107 => array('city_name' => 'FAZIL PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    108 => array('city_name' => 'FEROZ WATWAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    109 => array('city_name' => 'FKPCL POWER PLANT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    110 => array('city_name' => 'FORT ABBAS', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    111 => array('city_name' => 'GAGGO MANDI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    112 => array('city_name' => 'GAMBAT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    113 => array('city_name' => 'GAMBER', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    114 => array('city_name' => 'GARHA MORE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    115 => array('city_name' => 'GATWALA 199 / RB', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    116 => array('city_name' => 'GAWADER', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    117 => array('city_name' => 'GHAKKAR MANDI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    118 => array('city_name' => 'GHARIBWAL CEMENT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    119 => array('city_name' => 'GHARO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    120 => array('city_name' => 'GHAZI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    121 => array('city_name' => 'GHAZIABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    122 => array('city_name' => 'GHIKA GALI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    123 => array('city_name' => 'GHORA GALI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    124 => array('city_name' => 'GHOTKI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    125 => array('city_name' => 'GHOUR GHUSTI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    126 => array('city_name' => 'GHOUS PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    127 => array('city_name' => 'GILGIT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    128 => array('city_name' => 'GOJRA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    129 => array('city_name' => 'GOLARCHI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    130 => array('city_name' => 'GOTH MACHI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    131 => array('city_name' => 'GUJAR KHAN', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    132 => array('city_name' => 'GUJRANWALA', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    133 => array('city_name' => 'GUJRAT', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    134 => array('city_name' => 'GULYANA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    135 => array('city_name' => 'HAFIZABAD', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    136 => array('city_name' => 'HAJEERA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    137 => array('city_name' => 'HAKEEM ABAD', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    138 => array('city_name' => 'HALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    139 => array('city_name' => 'HANGU', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    140 => array('city_name' => 'HARAPPA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    141 => array('city_name' => 'HARIPUR', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    142 => array('city_name' => 'HARNAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    143 => array('city_name' => 'HAROONABAD', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    144 => array('city_name' => 'HASANABDAAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    145 => array('city_name' => 'HASEEB WAQAS MILLS', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    146 => array('city_name' => 'HASIL PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    147 => array('city_name' => 'HATIA BALA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    148 => array('city_name' => 'HATTAR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    149 => array('city_name' => 'HAVELI LAKHA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    150 => array('city_name' => 'HAVELIAN', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    151 => array('city_name' => 'HAZARA UNIVERSITY', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    152 => array('city_name' => 'HAZRO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    153 => array('city_name' => 'HEAD BALOKI ROAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    154 => array('city_name' => 'HEADMARALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    155 => array('city_name' => 'HUB CHOWKI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    156 => array('city_name' => 'HUJRA SHAH MUKEEM', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    157 => array('city_name' => 'HUSRI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    158 => array('city_name' => 'HYDERABAD', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    159 => array('city_name' => 'IQBAL ABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    160 => array('city_name' => 'IQBAL NAGAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    161 => array('city_name' => 'ISLAMABAD', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    162 => array('city_name' => 'JACABABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    163 => array('city_name' => 'JAFFARABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    164 => array('city_name' => 'JAHANIAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    165 => array('city_name' => 'JALALPUR BHATTIAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    166 => array('city_name' => 'JALALPUR JATTAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    167 => array('city_name' => 'JALALPURPIRWALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    168 => array('city_name' => 'JAMPUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    169 => array('city_name' => 'JAMSHERO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    170 => array('city_name' => 'JANDIA SHER KHAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    171 => array('city_name' => 'JARANWALA', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    172 => array('city_name' => 'JATOI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    173 => array('city_name' => 'JEHANGIRA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    174 => array('city_name' => 'JEHLUM', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    175 => array('city_name' => 'JHABRAN MANDI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    176 => array('city_name' => 'JHANG', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    177 => array('city_name' => 'JOHARABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    178 => array('city_name' => 'JOHI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    179 => array('city_name' => 'KABIRWALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    180 => array('city_name' => 'KAHAUTA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    181 => array('city_name' => 'KALAT', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    182 => array('city_name' => 'KALLAR KAHAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    183 => array('city_name' => 'KALLAR SYEDDAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    184 => array('city_name' => 'KALOR KOT', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    185 => array('city_name' => 'KAMALIA', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    186 => array('city_name' => 'KAMOKE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    187 => array('city_name' => 'KAMRA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    188 => array('city_name' => 'KAND KOT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    189 => array('city_name' => 'KANDIARO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    190 => array('city_name' => 'KANGAN PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    191 => array('city_name' => 'KANGRA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    192 => array('city_name' => 'KANJU', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    193 => array('city_name' => 'KANYAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    194 => array('city_name' => 'KAPCO POWER PLANT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    195 => array('city_name' => 'KARACHI', 'delivery_time' => '1 Day','initial_weight_limit'=>2, 'initial_weight_price'=>150,'additional_weight_price'=>100),
    196 => array('city_name' => 'KARAK', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    197 => array('city_name' => 'KARAM PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    198 => array('city_name' => 'KAROOR PAKA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    199 => array('city_name' => 'KAROR LAL EASAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    200 => array('city_name' => 'KASHMORE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    201 => array('city_name' => 'KASSOWAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    202 => array('city_name' => 'KASUR', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    203 => array('city_name' => 'KHAIR PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    204 => array('city_name' => 'KHAIRPUR MEERUS', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    205 => array('city_name' => 'KHAIRPUR TAMEWALI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    206 => array('city_name' => 'KHAN GHAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    207 => array('city_name' => 'KHAN PUR', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    208 => array('city_name' => 'KHANEWAL', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    209 => array('city_name' => 'KHANKA DOGRAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    210 => array('city_name' => 'KHANPUR MAHAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    211 => array('city_name' => 'KHARIAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    212 => array('city_name' => 'KHAS BEHAAL', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    213 => array('city_name' => 'KHOAZA KHAILA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    214 => array('city_name' => 'KHOSKI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    215 => array('city_name' => 'KHUDIAN KHAS', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    216 => array('city_name' => 'KHURRIANWALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    217 => array('city_name' => 'KHUSHAAB', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    218 => array('city_name' => 'KHUZDAR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    219 => array('city_name' => 'KHWERA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    220 => array('city_name' => 'KOHAT', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    221 => array('city_name' => 'KOT ADDU', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    222 => array('city_name' => 'KOT CHUTTA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    223 => array('city_name' => 'KOT MITHAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    224 => array('city_name' => 'KOT MOMIN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    225 => array('city_name' => 'KOT PINDI DAS', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    226 => array('city_name' => 'KOT RADHA KISHAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    227 => array('city_name' => 'KOT SAMABAH', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    228 => array('city_name' => 'KOTLA ARAB ALI KHAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    229 => array('city_name' => 'KOTLI', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    230 => array('city_name' => 'KOTLI BEHRAM', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    231 => array('city_name' => 'KOTLI LOHARAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    232 => array('city_name' => 'KOTRI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    233 => array('city_name' => 'KUCHLAK', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    234 => array('city_name' => 'KULACHI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    235 => array('city_name' => 'KUNDIAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    236 => array('city_name' => 'KUNRI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    237 => array('city_name' => 'LAHORE', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    238 => array('city_name' => 'LAKKI MARWAT', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    239 => array('city_name' => 'LALA MUSA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    240 => array('city_name' => 'LALIAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    241 => array('city_name' => 'LALLIANI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    242 => array('city_name' => 'LALPIR (THERMAL POWER)', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    243 => array('city_name' => 'LARKANA', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    244 => array('city_name' => 'LAWRENCE PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    245 => array('city_name' => 'LAYYAH', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    246 => array('city_name' => 'LIAQAT PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    247 => array('city_name' => 'LODHRAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    248 => array('city_name' => 'LORALAI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    249 => array('city_name' => 'LOWER TOPA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    250 => array('city_name' => 'MACHIKEY', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    251 => array('city_name' => 'MAILSI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    252 => array('city_name' => 'MALAKAND', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    253 => array('city_name' => 'MALAKWAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    254 => array('city_name' => 'MANA WLA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    255 => array('city_name' => 'MANAWALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    256 => array('city_name' => 'MANDI BAHAUDDIN', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    257 => array('city_name' => 'MANDI SAFDAR ABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    258 => array('city_name' => 'MANDI USMAN WALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    259 => array('city_name' => 'MANDIAN', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    260 => array('city_name' => 'MANDRA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    261 => array('city_name' => 'MANGA MANDI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    262 => array('city_name' => 'MANGLA (AJK)', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    263 => array('city_name' => 'MANGLA CANTT (AJK)', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    264 => array('city_name' => 'MANKERA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    265 => array('city_name' => 'MANKYLA STATION', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    266 => array('city_name' => 'MANSEHRA', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    267 => array('city_name' => 'MARDAN', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    268 => array('city_name' => 'MARI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    269 => array('city_name' => 'MASAR CAMP', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    270 => array('city_name' => 'MASTUNG', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    271 => array('city_name' => 'MATIYARI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    272 => array('city_name' => 'MATLI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    273 => array('city_name' => 'MATTA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    274 => array('city_name' => 'MEHER', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    275 => array('city_name' => 'MEHRAB PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    276 => array('city_name' => 'MIAN CHANNU', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    277 => array('city_name' => 'MIAN WALI QURESHAIN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    278 => array('city_name' => 'MIANI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    279 => array('city_name' => 'MIANWALI', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    280 => array('city_name' => 'MINCHINABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    281 => array('city_name' => 'MINGORA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    282 => array('city_name' => 'MIR PUR KHAS', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    283 => array('city_name' => 'MIR PUR METHELO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    284 => array('city_name' => 'MIRPUR (AJK)', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    285 => array('city_name' => 'MITHA TIWANA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    286 => array('city_name' => 'MITTHI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    287 => array('city_name' => 'MORE AIMANABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    288 => array('city_name' => 'MORE KHUNDA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    289 => array('city_name' => 'MORO', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    290 => array('city_name' => 'MOTRA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    291 => array('city_name' => 'MUCH', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    292 => array('city_name' => 'MULTAN', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    293 => array('city_name' => 'MURIDKE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    294 => array('city_name' => 'MURREE', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    295 => array('city_name' => 'MUZAFARABAD (AJK)', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    296 => array('city_name' => 'MUZAFFARGARH', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    297 => array('city_name' => 'NAROWAL', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    298 => array('city_name' => 'NAUSHKI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    299 => array('city_name' => 'NAWAB SHAH', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    300 => array('city_name' => 'NAWAN SHEHR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    301 => array('city_name' => 'NAWAY KALI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    302 => array('city_name' => 'NEW INDUSTRIAL AREA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    303 => array('city_name' => 'NIZAMABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    304 => array('city_name' => 'NONAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    305 => array('city_name' => 'NOOR COLONY', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    306 => array('city_name' => 'NOOR KOT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    307 => array('city_name' => 'NOORPUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    308 => array('city_name' => 'NOORPUR THAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    309 => array('city_name' => 'NORIABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    310 => array('city_name' => 'NOWSHERA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    311 => array('city_name' => 'NOWSHERA KALAN', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    312 => array('city_name' => 'NOWSHERA VIRKAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    313 => array('city_name' => 'NOWSHERO FEROZE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    314 => array('city_name' => 'NRTC (TELECOM STAFF COLLEGE)', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    315 => array('city_name' => 'NUDEARO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    316 => array('city_name' => 'NUNKANA SAB', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    317 => array('city_name' => 'OKARA', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    318 => array('city_name' => 'OLD HALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    319 => array('city_name' => 'P.O.F. (FACTORY & COLONY)', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    320 => array('city_name' => 'PABI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    321 => array('city_name' => 'PAHARPUR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    322 => array('city_name' => 'PAKPATTAN', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    323 => array('city_name' => 'PANOAQIL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    324 => array('city_name' => 'PAROA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    325 => array('city_name' => 'PASROOR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    326 => array('city_name' => 'PASROOR ROAD AND VILLAGES', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    327 => array('city_name' => 'PATOKI', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    328 => array('city_name' => 'PATRIATA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    329 => array('city_name' => 'PEER MAHAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    330 => array('city_name' => 'PESHAWAR', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    331 => array('city_name' => 'PEZU', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    332 => array('city_name' => 'PHALIA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    333 => array('city_name' => 'PIND DADAN KHAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    334 => array('city_name' => 'PINDI BHATIAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    335 => array('city_name' => 'PINDI GHEB', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    336 => array('city_name' => 'PINDI GUJRAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    337 => array('city_name' => 'PIPLAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    338 => array('city_name' => 'PIR BABA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    339 => array('city_name' => 'PISHIN', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    340 => array('city_name' => 'PITARO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    341 => array('city_name' => 'PLANDARI / SADHNOTI (AJK)', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    342 => array('city_name' => 'PMA KAKUL', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    343 => array('city_name' => 'POONCH (AJK)', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    344 => array('city_name' => 'PUNGIRAYIN', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    345 => array('city_name' => 'PUNWAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    346 => array('city_name' => 'QABAL', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    347 => array('city_name' => 'QABOOLA SHARIF', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    348 => array('city_name' => 'QADIR PUR RAWAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    349 => array('city_name' => 'QAIDABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    350 => array('city_name' => 'QAMAR MASHANI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    351 => array('city_name' => 'QILA DEEDAR SING', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    352 => array('city_name' => 'QILA SAIB SINGH', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    353 => array('city_name' => 'QUETTA', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    354 => array('city_name' => 'RAHIM YAR KHAN', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    355 => array('city_name' => 'RAIWIND', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    356 => array('city_name' => 'RAJA JANG', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    357 => array('city_name' => 'RAJAN PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    358 => array('city_name' => 'RAJANA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    359 => array('city_name' => 'RAJAR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    360 => array('city_name' => 'RAMAK', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    361 => array('city_name' => 'RANI PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    362 => array('city_name' => 'RAO KHAN WALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    363 => array('city_name' => 'RATO DEARO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    364 => array('city_name' => 'RAWALAKOT (AJK)', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    365 => array('city_name' => 'RAWALPINDI', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    366 => array('city_name' => 'RAWAT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    367 => array('city_name' => 'RENALA KHURD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    368 => array('city_name' => 'RISALPUR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    369 => array('city_name' => 'ROHRI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    370 => array('city_name' => 'RUBWA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    371 => array('city_name' => 'SADIQABAD', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    372 => array('city_name' => 'SAFDARABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    373 => array('city_name' => 'SAHIWAL', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    374 => array('city_name' => 'SAIDU SHARIF', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    375 => array('city_name' => 'SAJAWAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    376 => array('city_name' => 'SAKRAND', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    377 => array('city_name' => 'SAMANDARI', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    378 => array('city_name' => 'SANGAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    379 => array('city_name' => 'SANGLA HILL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    380 => array('city_name' => 'SANJWAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    381 => array('city_name' => 'SARAYE NORANG', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    382 => array('city_name' => 'SARDAR GARH', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    383 => array('city_name' => 'SARDARYAB', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    384 => array('city_name' => 'SARGODHA', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    385 => array('city_name' => 'SARI ALAMGIR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    386 => array('city_name' => 'SAWABI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    387 => array('city_name' => 'SAWAT', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    388 => array('city_name' => 'SEHWAN SHARIF', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    389 => array('city_name' => 'SHABQADAR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    390 => array('city_name' => 'SHADAD KOT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    391 => array('city_name' => 'SHADIWAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    392 => array('city_name' => 'SHAH PUR CHAKAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    393 => array('city_name' => 'SHAHDAD PUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    394 => array('city_name' => 'SHAHKOT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    395 => array('city_name' => 'SHAHPUR SADDAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    396 => array('city_name' => 'SHAKARGARH', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    397 => array('city_name' => 'SHAM KOT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    398 => array('city_name' => 'SHAMS ABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    399 => array('city_name' => 'SHANGLA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    400 => array('city_name' => 'SHEEDO', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    401 => array('city_name' => 'SHEIKHUPURA', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    402 => array('city_name' => 'SHERGARH', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    403 => array('city_name' => 'SHEWA ADDA', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    404 => array('city_name' => 'SHIKARPUR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    405 => array('city_name' => 'SHIMLA HILL', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    406 => array('city_name' => 'SHORKOT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    407 => array('city_name' => 'SHUJABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    408 => array('city_name' => 'SIALKOT', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    409 => array('city_name' => 'SIBI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    410 => array('city_name' => 'SIHALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    411 => array('city_name' => 'SIKANDARABAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    412 => array('city_name' => 'SILANWALI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    413 => array('city_name' => 'SIRAYE MUHAJIR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    414 => array('city_name' => 'SKARDU', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    415 => array('city_name' => 'SMAAL IND ESTATE. DASKA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    416 => array('city_name' => 'SOHAWA ONLY MAIN GT ROAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    417 => array('city_name' => 'SUKKUR', 'delivery_time' => '2-3 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    418 => array('city_name' => 'SUMBRIAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    419 => array('city_name' => 'SUNDER ADDA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    420 => array('city_name' => 'SWABI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    421 => array('city_name' => 'SYED WALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    422 => array('city_name' => 'TAKHT-E-BHAI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    423 => array('city_name' => 'TALAGUNG', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    424 => array('city_name' => 'TALHAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    425 => array('city_name' => 'TALVANDI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    426 => array('city_name' => 'TANDLAWALA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    427 => array('city_name' => 'TANDO ADAM', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    428 => array('city_name' => 'TANDO ALLAHYAR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    429 => array('city_name' => 'TANDO GHULAM ALI', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    430 => array('city_name' => 'TANDO JAM', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    431 => array('city_name' => 'TANDO JAN MUHAMMAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    432 => array('city_name' => 'TANDO MOHD KHAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    433 => array('city_name' => 'TANGI', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    434 => array('city_name' => 'TANK', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    435 => array('city_name' => 'TARBELA DAM', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    436 => array('city_name' => 'TARNOL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    437 => array('city_name' => 'TAUNSA SHARIF', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    438 => array('city_name' => 'TAXLA', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    439 => array('city_name' => 'THATTA', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    440 => array('city_name' => 'THEENG MORE (ALLAHABAD)', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    441 => array('city_name' => 'THULL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    442 => array('city_name' => 'TIBBA SULTANPURA', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    443 => array('city_name' => 'TIMARGARAH', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    444 => array('city_name' => 'TOBA TEK SINGH', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    445 => array('city_name' => 'TOPI (GIK UNIVERSITY AREA ONLY)*', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    446 => array('city_name' => 'TRANDA SAWAY KHAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    447 => array('city_name' => 'TURBAT', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    448 => array('city_name' => 'UBARO', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    449 => array('city_name' => 'UCH SHRIF', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    450 => array('city_name' => 'UGGOKE', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    451 => array('city_name' => 'UMER KOT', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    452 => array('city_name' => 'UPPER DIR', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    453 => array('city_name' => 'USTA MUHAMMAD', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    454 => array('city_name' => 'VEHARI', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    455 => array('city_name' => 'VILLAGE SIAL', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    456 => array('city_name' => 'WAH CANTT', 'delivery_time' => '4-5 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    457 => array('city_name' => 'WAN RAHDA RAM', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    458 => array('city_name' => 'WAPDA COLONY (AJK)', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    459 => array('city_name' => 'WARBATTAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    460 => array('city_name' => 'WAZIRABAD', 'delivery_time' => '3-4 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    461 => array('city_name' => 'YAZMAN', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    462 => array('city_name' => 'ZAFARWAL', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    463 => array('city_name' => 'ZAHIR PIR', 'delivery_time' => '5-6 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    464 => array('city_name' => 'ZHOB', 'delivery_time' => '6-7 DAYS','initial_weight_limit'=>2, 'initial_weight_price'=>250,'additional_weight_price'=>160),
    465 => array('city_name' => 'No City', 'delivery_time' => '0 DAYS','initial_weight_limit'=>0, 'initial_weight_price'=>0,'additional_weight_price'=>0),
);

        $cc=0;
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::statement('TRUNCATE cities');
        DB::statement('ALTER TABLE cities AUTO_INCREMENT = 1');
        foreach ($cities as $key=>$val){
            $cc++;
            echo $cc . "\n";
            echo 'city' . $val['city_name']. "\n";
            echo 'delivery' . $val['delivery_time']. "\n";
            City::create([
                'city_name'=>$val['city_name'],
                'delivery_time'=>$val['delivery_time'],
                'initial_weight_limit'=>$val['initial_weight_limit'],
                'initial_weight_price'=>$val['initial_weight_price'],
                'additional_weight_price'=>$val['additional_weight_price'],
                'is_enabled'=>1
            ]);

        }
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
